version: '3'
services:
  db:
    container_name: sweet-space-db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - SweetSpace

  app:
    build: ./
    container_name: sweet-space
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - SweetSpace

networks:
  SweetSpace:
    driver: bridge

volumes:
  pg_data: {}
